### ISSUE TITLE
Binding .net Core Runtime into Electron/Node

### ISSUE THREAD

**Issue by TFSThiagoBR98** [TFSThiagoBR98/Libresub#1]
This is a task list for implement .net Core into Electron/Node

## Tasks

- [ ] Integrate CLR on Node/v8
- [ ] Integrate Node on CLR
- [ ] Make a CLR library to Integract with Electron.
- [ ] Make a way to use Asp.net Core to rendering pages.
- [ ] ...
